date: 2019-10-30 10:51:37 UTC
# SITE CONFIGURATION
baseurl: #"/Type-on-Strap"
default_locale: "pt-BR"

url: "https://projetokube-documentacao.github.io"
title: Projeto Kube # site's title
description: "Computação em nuvem, Devops e educação" # used by search engines

defaults:
  - scope:
      path: "" # an empty string here means all necessary files are in the project
    values:
      image: assets/img/projetokube.png # seo tag
  - scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  avatar: assets/img/projetokube.png
  color_image: /assets/img/lineart.png # In post when you set color
  favicon: assets/favicon.ico

  # Header and footer text
  header_text: Computação em nuvem, Devops e educação
  header_feature_image: assets/img/pexels/triangular.jpeg
  footer_text: >
    Powered by <a href="https://jekyllrb.com/">Jekyll</a> com o tema <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

  # Blog
  excerpt: truncate # true Or "truncate" (first 250 characters), "false" to disable

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "CBSIIFSLagarto/projetokube-documentacao"
  instagram:
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_overflow:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Sharing options
  share_buttons:
    facebook: false
    twitter: true
    tumblr:
    pinterest:
    pocket:
    reddit: true
    linkedin:
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Próximo post"
  str_previous_post: "Post anterior"
  str_next_page: "Próximo"
  str_previous_page: "Anterior"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Post navigation
  post_navigation: true

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"



# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name
  projetos:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-avatar
  - jekyll-gist
  - jekyll-mentions
  # - jekyll-relative-links # https://github.com/benbalter/jekyll-relative-links
  - jekyll-sitemap # https://github.com/jekyll/jekyll-sitemap
  - jemoji
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

keep_files: [assets/img]

feed:
  path: atom.xml
#  collections:
#    - projetos
#    - protfolio


# theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
# remote_theme: sylhare/Type-on-Strap # If using as a remote_theme in github

search:
  noResultText: 'Nenhum resultado encontrado.'
  resultLimite: 10

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  

compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]

relatedPosts:
  maxRelated: 4
  minCommonTags: 2
